[manager]
show_hidden = true
show_symlink = true
mouse_events = [ 'click', 'scroll', 'touch', "move", "drag"]
linemode = "size"

[opener]
edit = [{run = 'v "$@', block = true}]

[tasks]
image_bound = [0,0]

[preview]
max_width = 1200
max_height = 800 
image_quality = 90
ueberzug_scale = 4.0
ueberzug_offset = [0.5,0.5, 2000, 2000]
image_filter = "lanczos3"

