[[language]]
name = "rust"
auto-format = false
[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript", "--config", "/Users/weston/Projects/WOSAI/FRONTEND/emenu-mini-core"] }
auto-format = true
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }
