[options]
    bootstrap_after = 'myspacevim#after'
    colorscheme = "gruvbox"
    #colorscheme = "carbon"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    autocomplete_method = "coc"
    snippet_engine = "ultisnips"

# enabled_formater=["remark", "prettier"]
# lint_engine="ale"
# lint_engine="syntastic"

# enable_neomake = true
# enable_ale = true
#lint_on_the_fly = true
#enable_vimfiler_gitstatus = true
#disabled_plugins = ["vim-signify"]
# left sections of statusline
statusline_left_sections = [
  'winnr',
  #'major mode',
  'filename',
  #'fileformat',
  #'minor mode lighters',
  #'search status'
]
# right sections of statusline
statusline_right_sections = [
  'cursorpos',
  'percentage',
  'input method',
  'version control info',
#'date',
#  'time'
]
# Enable autocomplete layer

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# [[layers]]
#name = "lang#typescript"

 [[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "ctrlp"

[[layers]]
  name = "git"
  git_plugin = 'fugitive'

[[layers]]
  name = "fzf"

[[layers]]
  name = "debug"

[[layers]]
  name = "treesitter"

[[layers]]
  name = "VersionControl"
# [[layers]]
  # name = "lsp"
#

[[layers]]
    name = "incsearch"

[[custom_plugins]]
name = "michaeldyrynda/carbon"
merged = false

[[custom_plugins]]
name = "chemzqm/wxapp.vim"
merged = false

[[custom_plugins]]
name = "gelguy/wilder.nvim"
merged = false

[[custom_plugins]]
name = "nvim-telescope/telescope.nvim"
merged = false
# nnoremap <leader>fG <cmd>Telescope live_grep<cr>
hook_add = '''
  nnoremap <leader>f1 <cmd>Telescope find_files<cr>
  nnoremap <leader>ff <cmd>Telescope git_files<cr>
  nnoremap <leader>fg <cmd>Telescope git_status<cr>
  nnoremap <leader>ft <cmd>Telescope treesitter<cr>
  nnoremap <leader>fb <cmd>Telescope buffers<cr>
  nnoremap <leader>fh <cmd>Telescope help_tags<cr>
  nnoremap <leader>f1 <cmd>lua require('telescope.builtin').find_files()<cr>
  nnoremap <leader>ff <cmd>lua require('telescope.builtin').git_files()<cr>
  nnoremap <leader>fg <cmd>lua require('telescope.builtin').git_status()<cr>
  nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
  nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>
'''

[[custom_plugins]]
name = "nvim-lua/plenary.nvim"
merged = false

[[custom_plugins]]
name = "windwp/nvim-spectre"
merged = false
hook_add = '''

  nnoremap <leader>S :lua require('spectre').open()<CR>
  nnoremap <leader>sw :lua require('spectre').open_visual({select_word=true})<CR>
  vnoremap <leader>s :lua require('spectre').open_visual()<CR>
  nnoremap <leader>sp viw:lua require('spectre').open_file_search()<cr>
'''

[[custom_plugins]]
name = "voldikss/vim-floaterm"
merged = false

[[custom_plugins]]
name = "mkarmona/materialbox"
merged = false

# [[custom_plugins]]
 # name = 'lewis6991/gitsigns.nvim'
  # merged = false
  # hook_add = '''
  # lua << EOF
  # require('gitsigns').setup({})
# EOF
# '''

[[custom_plugins]]
name = "sindrets/diffview.nvim"
merged = false
hook_add = '''
  nnoremap <leader>d :DiffviewOpen -uno<cr>
'''

#[[custom_plugins]]
#name = "mhartington/nvim-typescript"
#merged = false
#for = ['javascript', 'javascript.jsx','typescript']
#do = './install.sh'
